---
engines:
  sonar-java:
    enabled: true
    channel: beta
    checks:
      squid:S00112: # Requires dedicated exceptions even for tests
        enabled: false
    config:
      tests_patterns:
        - src/test/**
exclude_paths:
  - build/
  - fixtures/
  - gradle/
  - .gradle/
