/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// FIXME
public class Library {
  public static void main(String[] args) {
  }

	public void foo() {
		for (int i = 0; i < 10; i++) {
			for (int k = 0; k < 20; k++) {
				System.out.println("Hello");
			}
		}

		for (int i = 0; i < 10; i++) {			// only references 'i'
			for (int k = 0; k < 20; i++) {		// references both 'i' and 'k'
				System.out.println("Hello");
			}
			for (int k = 0; k < 20; i++) {		// references both 'i' and 'k'
				System.out.println("Hello");
			}
			for (int k = 0; k < 20; i++) {		// references both 'i' and 'k'
				System.out.println("Hello");
			}
		}
	}
}
