/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// FIXME
public class Library {
  public static void main(String[] args) {
  }

	public void foo() {
		for (int i = 1; i != 10; i += 2) {
			for (int k = 0; k < 20; k++) {
				System.out.println("Hello");
			}
		}
	}
}
